// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 02.03.2026, 19:19:51
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.cjs";
const config = [
{"content":{"files":["C:/Users/Alex/Desktop/mini_bitrix/nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Alex/Desktop/mini_bitrix/nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Alex/Desktop/mini_bitrix/nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Alex/Desktop/mini_bitrix/nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Alex/Desktop/mini_bitrix/nuxt/plugins/**/*.{js,ts,mjs}","C:/Users/Alex/Desktop/mini_bitrix/nuxt/composables/**/*.{js,ts,mjs}","C:/Users/Alex/Desktop/mini_bitrix/nuxt/utils/**/*.{js,ts,mjs}","C:/Users/Alex/Desktop/mini_bitrix/nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Alex/Desktop/mini_bitrix/nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Alex/Desktop/mini_bitrix/nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Alex/Desktop/mini_bitrix/nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;