# Generated by Django 4.2.16 on 2026-04-02 09:19

from django.db import migrations, models
import django.db.models.deletion


def backfill_site_client_from_token(apps, schema_editor):
    Site = apps.get_model('tracker', 'Site')
    Client = apps.get_model('clients', 'Client')
    for site in Site.objects.filter(client__isnull=True).iterator():
        token = (site.token or "").strip()
        if not token:
            continue
        client = Client.objects.filter(api_key=token, is_active=True).first()
        if not client:
            continue
        site.client_id = client.id
        site.save(update_fields=['client'])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_auto_respond_enabled_and_more'),
        ('tracker', '0005_visit_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_sites', to='clients.client'),
        ),
        migrations.RunPython(backfill_site_client_from_token, noop_reverse),
    ]
