# Generated by Django 4.2.16 on 2026-04-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_options_alter_client_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auto_respond_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable auto response'),
        ),
        migrations.AddField(
            model_name='client',
            name='auto_respond_subject',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Auto response subject'),
        ),
        migrations.AddField(
            model_name='client',
            name='auto_respond_template',
            field=models.TextField(blank=True, default='', verbose_name='Auto response template'),
        ),
        migrations.AddField(
            model_name='client',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Notification email'),
        ),
        migrations.AddField(
            model_name='client',
            name='stale_lead_hours',
            field=models.PositiveSmallIntegerField(default=24, verbose_name='Stale lead threshold (hours)'),
        ),
        migrations.AddField(
            model_name='client',
            name='webhook_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Webhook timeout (sec)'),
        ),
        migrations.AddField(
            model_name='client',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Webhook URL'),
        ),
    ]
