# Generated by Django 4.2.16 on 2026-04-01 20:53

import re

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _normalize_phone(value: str) -> str:
    raw = (value or "").strip()
    if not raw:
        return ""
    digits = re.sub(r"\D", "", raw)
    if len(digits) < 7:
        return ""
    if len(digits) == 11 and digits.startswith("8"):
        digits = f"7{digits[1:]}"
    if len(digits) == 10:
        digits = f"7{digits}"
    return f"+{digits}"


def _normalize_email(value: str) -> str:
    raw = (value or "").strip().lower()
    if not raw or "@" not in raw:
        return ""
    return raw


def bootstrap_pipelines_and_sync_leads(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    Pipeline = apps.get_model("leads", "Pipeline")
    PipelineStage = apps.get_model("leads", "PipelineStage")
    Lead = apps.get_model("leads", "Lead")

    default_stages = (
        {"name": "Новый", "order": 1, "color": "#3B82F6", "is_closed_stage": False},
        {"name": "В работе", "order": 2, "color": "#06B6D4", "is_closed_stage": False},
        {"name": "Квалифицирован", "order": 3, "color": "#14B8A6", "is_closed_stage": False},
        {"name": "Предложение", "order": 4, "color": "#F59E0B", "is_closed_stage": False},
        {"name": "Сделка", "order": 5, "color": "#22C55E", "is_closed_stage": True},
    )

    for client in Client.objects.all().iterator():
        pipeline = Pipeline.objects.filter(client_id=client.id, is_default=True).order_by("id").first()
        if pipeline is None:
            pipeline = Pipeline.objects.filter(client_id=client.id).order_by("id").first()
            if pipeline is None:
                pipeline = Pipeline.objects.create(client_id=client.id, name="Основная", is_default=True)
            elif not pipeline.is_default:
                pipeline.is_default = True
                pipeline.save(update_fields=["is_default", "updated_at"])

        existing_by_order = {item.order: item for item in PipelineStage.objects.filter(pipeline_id=pipeline.id)}
        for stage_data in default_stages:
            stage = existing_by_order.get(stage_data["order"])
            if stage is None:
                PipelineStage.objects.create(pipeline_id=pipeline.id, **stage_data)
                continue
            fields_to_update = []
            for field_name in ("name", "color", "is_closed_stage"):
                expected = stage_data[field_name]
                if getattr(stage, field_name) != expected:
                    setattr(stage, field_name, expected)
                    fields_to_update.append(field_name)
            if fields_to_update:
                stage.save(update_fields=fields_to_update)

        first_stage = (
            PipelineStage.objects.filter(pipeline_id=pipeline.id, is_active=True)
            .order_by("order", "id")
            .first()
        )
        if first_stage:
            Lead.objects.filter(client_id=client.id, stage_id__isnull=True).update(stage_id=first_stage.id)

    for lead in Lead.objects.all().iterator():
        normalized_phone = _normalize_phone(getattr(lead, "phone", "") or "")
        normalized_email = _normalize_email(getattr(lead, "email", "") or "")
        updates = {}
        if getattr(lead, "normalized_phone", "") != normalized_phone:
            updates["normalized_phone"] = normalized_phone
        if getattr(lead, "normalized_email", "") != normalized_email:
            updates["normalized_email"] = normalized_email
        if updates:
            for key, value in updates.items():
                setattr(lead, key, value)
            lead.save(update_fields=list(updates.keys()) + ["updated_at"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0006_client_auto_respond_enabled_and_more'),
        ('leads', '0004_alter_lead_name_alter_lead_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Создан лид'), ('stage_moved', 'Перемещение по стадиям'), ('note_added', 'Добавлена заметка'), ('scheduled', 'Запланирован контакт'), ('duplicate_merged', 'Объединен дубликат'), ('score_updated', 'Обновлен скоринг'), ('auto_response', 'Автоответ'), ('notified', 'Уведомление')], max_length=64, verbose_name='Тип действия')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Активность лида',
                'verbose_name_plural': 'Активности лидов',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основная', max_length=120, verbose_name='Название')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Воронка',
                'verbose_name_plural': 'Воронки',
                'ordering': ('client_id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет')),
                ('auto_action', models.JSONField(blank=True, null=True, verbose_name='Авто-действия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_closed_stage', models.BooleanField(default=False, verbose_name='Финальная стадия')),
            ],
            options={
                'verbose_name': 'Стадия воронки',
                'verbose_name_plural': 'Стадии воронки',
                'ordering': ('pipeline_id', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('color', models.CharField(default='#64748B', max_length=7, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Тег лида',
                'verbose_name_plural': 'Теги лидов',
                'ordering': ('client_id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='WidgetVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название варианта')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Конфигурация')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Показы')),
                ('conversions', models.PositiveIntegerField(default=0, verbose_name='Конверсии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Вариант виджета',
                'verbose_name_plural': 'Варианты виджета',
                'ordering': ('client_id', '-is_active', 'name'),
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='lead',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Оценочная ценность'),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_contact_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующий контакт'),
        ),
        migrations.AddField(
            model_name='lead',
            name='normalized_email',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Email (норм.)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Телефон (норм.)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Скоринг'),
        ),
        migrations.AddField(
            model_name='lead',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Session ID'),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='lead',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Visitor ID'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['client', 'stage', 'created_at'], name='leads_lead_client__aae0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['client', 'normalized_phone'], name='leads_lead_client__de26c8_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['client', 'normalized_email'], name='leads_lead_client__1f498c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['client', 'score'], name='leads_lead_client__f5ea0e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['client', 'last_activity_at'], name='leads_lead_client__2f9cba_idx'),
        ),
        migrations.AddField(
            model_name='widgetvariant',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_variants', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='tag',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_tags', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='leads.pipeline', verbose_name='Воронка'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead', verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.pipelinestage', verbose_name='Стадия'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='leads', to='leads.tag', verbose_name='Теги'),
        ),
        migrations.RunPython(bootstrap_pipelines_and_sync_leads, noop_reverse),
        migrations.AddConstraint(
            model_name='widgetvariant',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='leads_unique_widget_variant_name_per_client'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='leads_unique_tag_name_per_client'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(fields=('pipeline', 'order'), name='leads_unique_stage_order_per_pipeline'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('client',), name='leads_unique_default_pipeline_per_client'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', 'action_type', 'created_at'], name='leads_leada_lead_id_c6389c_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', 'created_at'], name='leads_leada_lead_id_b4ac2c_idx'),
        ),
    ]
