# Generated by Django 4.2.16 on 2026-04-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_leadactivity_pipeline_pipelinestage_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='tracker_dedup_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=96, verbose_name='Tracker dedup key'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tracker_submission_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Tracker submission ID'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('tracker_dedup_key', ''), _negated=True), fields=('client', 'tracker_dedup_key'), name='leads_unique_tracker_dedup_key_per_client'),
        ),
    ]
